x-runtipi:
  schema_version: 2
services:
  caddy:
    image: ghcr.io/coreruleset/coraza-crs:4.25.0-caddy-alpine-202604120304
    restart: unless-stopped
    command:
      - >
        /entrypoint.sh

        # Write Caddyfile
        cat << 'EOF' > /etc/caddy/Caddyfile
        # Ensure Coraza WAF runs first - this must be included for Coraza to be working
        {
          order coraza_waf first
          log {
            output stdout
            format console
            level INFO
          }
        }

        :3000 {

          # Paths that must bypass Coraza entirely
          @waf_bypass path /api/* /s3-storage/*

          # Handle bypassed paths first, WITHOUT invoking coraza_waf
          handle_path /api/* {
            reverse_proxy http://ente-museum_ladral-caddy-1:8080
          }

          handle /s3-storage/* {
            reverse_proxy http://ente-museum_ladral-caddy-1:8080
          }

          # All other requestts goes through Coraza
          handle {
            # Load Coraza configuration
            coraza_waf {

              # Main configuration file                          
              include /opt/coraza/config/coraza.conf

              # User defined configuration files
              include /opt/coraza/config.d/*.conf

              # OWASP Core Rule Set (CRS) Setup
              include /opt/coraza/config/crs-setup.conf

              include /opt/coraza/owasp-crs/plugins/*-config.conf
              include /opt/coraza/owasp-crs/plugins/*-before.conf

              # User plugins Setup
              include /opt/coraza/plugins/*-config.conf
              include /opt/coraza/plugins/*-before.conf

              # OWASP Core Rule Set (CRS)
              include /opt/coraza/owasp-crs/rules/*.conf

              include /opt/coraza/owasp-crs/plugins/*-after.conf

              # User plugins after
              include /opt/coraza/plugins/*-after.conf

              # Other baked in rule sets or configurations
              include /opt/coraza/rules/*.conf

              # User defined rule sets
              include /opt/coraza/rules.d/*.conf

              # Any overrides specified in env vars
              include /opt/coraza/overrides/*.conf
            }

            reverse_proxy ente-web:3000
          }
        }
        EOF

        # Launch Caddy
        exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    entrypoint: /bin/sh -c
    x-runtipi:
      internal_port: 3000
      is_main: true
  ente-web:
    image: ghcr.io/ente/web:062c7066883b37978b6dea7b7703d4efc5f13351
    restart: unless-stopped
    environment:
      - ENTE_PHOTOS_ORIGIN=https://${APP_EXPOSED_DOMAIN:-${APP_LOCAL_DOMAIN}}
      - ENTE_API_ORIGIN=https://${APP_EXPOSED_DOMAIN:-${APP_LOCAL_DOMAIN}}/api
